version: '3.8'
services:
  my-tickets:
    container_name: my-tickets
    image: atxpaul/my-tickets:0.0.1
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      - EXTERNAL_PORT=8080
    depends_on:
      - web
  web:
    image: nginx:1.21.4-alpine
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8081:80"