name: Node.js CI/CD full pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
              env:
                ADMIN_MAIL: ${{ secrets.ADMIN_MAIL }}
                GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
                GMAIL_USER: ${{ secrets.GMAIL_USER }}
                JWT_SECRET: ${{ secrets.JWT_SECRET }}
                JWT_TIME: ${{ secrets.JWT_TIME }}
                MONGO_URL: ${{ secrets.MONGO_URL }}
                SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
